import { createClient } from '@supabase/supabase-js';
import { Blueprint, GeneratedProject } from '@/lib/code-generator/types';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || '',
  process.env.SUPABASE_SERVICE_ROLE_KEY || ''
);

export interface ProjectRecord {
  id: string;
  name: string;
  slug: string | null;
  description: string | null;
  status: 'generating' | 'completed' | 'failed';
  total_files: number;
  technologies: string[];
  created_at: string;
  updated_at: string;
  user_id: string;
  owner_id?: string; // For hub_schema compatibility
  github_url: string | null;
  github_repo_id: number | null;
  // Joined fields
  blueprints?: BlueprintRecord[];
}

export interface BlueprintRecord {
  id: string;
  project_id: string;
  version: number;
  title: string | null;
  description: string | null;
  content: string; // JSON string of Blueprint
  code_json: string | null; // JSON string of GeneratedFiles
  created_at: string;
}

export interface ProjectGenerationStep {
  id: string;
  project_id: string;
  step_name: string;
  step_type?: string;
  metadata?: any;
  status: 'pending' | 'in-progress' | 'completed' | 'failed';
  started_at?: string;
  completed_at?: string;
  details?: string;
  created_at?: string;
}

// Legacy type for frontend compatibility (mapped)
export interface GeneratedProjectRecord extends ProjectRecord {
  // Fields mapped from BlueprintRecord
  blueprint: Blueprint;
  generated_files: GeneratedProject;
  project_name: string; // mapped to name
  project_slug: string; // mapped to slug
  current_step: string | null; // Deprecated/Project Status
  error_message: string | null;
  api_endpoints: number; // calculated
  components: number; // calculated
  completed_at: string | null;
}

export class ProjectDatabase {
  /**
   * Create a new project and initial blueprint
   */
  static async createProject(
    userId: string,
    blueprint: Blueprint,
    generatedProject: GeneratedProject
  ): Promise<ProjectRecord> {
    // 1. Create Project
    const { data: project, error: projectError } = await supabase
      .from('projects')
      .insert({
        user_id: userId,
        owner_id: userId, // Added for hub_schema compatibility
        name: blueprint.projectName,
        slug: generatedProject.name,
        description: blueprint.description,
        vibe: blueprint.description || blueprint.projectName, // Added for hub_schema compatibility
        status: 'generating',
        total_files: generatedProject.summary.totalFiles,
        technologies: generatedProject.summary.technologies,
      })
      .select()
      .single();

    if (projectError) throw projectError;

    // 2. Create Blueprint
    const { error: blueprintError } = await supabase
      .from('blueprints')
      .insert({
        project_id: project.id,
        user_id: userId,
        version: 1,
        title: 'Initial Generation',
        description: 'First draft generated by VibeCode Mentor',
        content: JSON.stringify(blueprint),
        code_json: JSON.stringify(generatedProject),
      });

    if (blueprintError) {
      // Cleanup project if blueprint fails (best effort)
      await supabase.from('projects').delete().eq('id', project.id);
      throw blueprintError;
    }

    return project;
  }

  /**
   * Create an empty project (for later agent population)
   */
  static async createEmptyProject(
    userId: string,
    name: string,
    description: string
  ): Promise<ProjectRecord> {
    const baseSlug = name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
    const slug = `${baseSlug}-${Math.random().toString(36).substring(2, 8)}`;

    const { data: project, error } = await supabase
      .from('projects')
      .insert({
        user_id: userId,
        owner_id: userId, // Added for hub_schema compatibility
        name: name,
        slug: slug,
        description: description,
        vibe: description || name, // Added for hub_schema compatibility
        status: 'generating',
        total_files: 0,
        technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
      })
      .select()
      .single();

    if (error) throw error;
    return project;
  }

  /**
   * Get project with latest blueprint
   */
  static async getProject(projectId: string, retries: number = 2): Promise<GeneratedProjectRecord> {
    for (let i = 0; i <= retries; i++) {
      try {
        const { data: project, error } = await supabase
          .from('projects')
          .select('*, blueprints(*)')
          .eq('id', projectId)
          .single();

        if (error) throw error;
        return this.mapToLegacy(project);
      } catch (error) {
        if (i === retries) throw error;
        console.warn(`Retry ${i + 1}/${retries} for fetching project...`);
        await new Promise(r => setTimeout(r, 500 * (i + 1)));
      }
    }
    throw new Error("Failed to fetch project after retries");
  }

  /**
   * Get all projects for a user
   */
  static async getUserProjects(userId: string, retries: number = 2): Promise<ProjectRecord[]> {
    for (let i = 0; i <= retries; i++) {
      try {
        const { data, error } = await supabase
          .from('projects')
          .select('*')
          .eq('user_id', userId)
          .order('created_at', { ascending: false });

        if (error) throw error;
        return data;
      } catch (error) {
        if (i === retries) throw error;
        console.warn(`Retry ${i + 1}/${retries} for fetching user projects...`);
        await new Promise(r => setTimeout(r, 500 * (i + 1)));
      }
    }
    return [];
  }

  /**
   * Update project status
   */
  static async updateProjectStatus(
    projectId: string,
    status: 'generating' | 'completed' | 'failed',
    errorMessage?: string
  ): Promise<void> {
    // We don't have error_message column in schema yet, ignore for now or add it
    // Schema has status.
    const update: any = { status, updated_at: new Date().toISOString() };

    const { error } = await supabase
      .from('projects')
      .update(update)
      .eq('id', projectId);

    if (error) throw error;
  }

  /**
   * Update GitHub URL
   */
  static async updateProjectGithubUrl(
    projectId: string,
    githubUrl: string,
    repoId: number
  ): Promise<void> {
    const { error } = await supabase
      .from('projects')
      .update({
        github_url: githubUrl,
        github_repo_id: repoId,
        status: 'completed',
        updated_at: new Date().toISOString(),
      })
      .eq('id', projectId);

    if (error) throw error;
  }

  /**
   * Delete project
   */
  static async deleteProject(projectId: string): Promise<void> {
    const { error } = await supabase
      .from('projects')
      .delete()
      .eq('id', projectId);

    if (error) throw error;
  }

  /**
   * Save a new blueprint version (after scaffolding/modification)
   */
  static async saveGeneratedBlueprint(
    projectId: string,
    blueprint: Blueprint,
    generatedProject: GeneratedProject,
    title: string = 'Agent Generation',
    retries: number = 2
  ): Promise<void> {
    for (let i = 0; i <= retries; i++) {
      try {
        // 1. Get latest version
        const { data: latest } = await supabase
          .from('blueprints')
          .select('version')
          .eq('project_id', projectId)
          .order('version', { ascending: false })
          .limit(1)
          .single();

        const newVersion = (latest?.version || 0) + 1;

        // 2. Insert new blueprint
        // Fetch user_id from project first
        const { data: project } = await supabase
          .from('projects')
          .select('user_id')
          .eq('id', projectId)
          .single();

        const { error } = await supabase
          .from('blueprints')
          .insert({
            project_id: projectId,
            user_id: project?.user_id,
            version: newVersion,
            title: title,
            description: 'Generated by Agent',
            content: JSON.stringify(blueprint),
            code_json: JSON.stringify(generatedProject),
          });

        if (error) throw error;

        // 3. Update Project Summary (total files, etc)
        await supabase.from('projects').update({
          total_files: generatedProject.summary.totalFiles,
          technologies: generatedProject.summary.technologies,
          updated_at: new Date().toISOString()
        }).eq('id', projectId);

        return;
      } catch (error) {
        if (i === retries) throw error;
        console.warn(`Retry ${i + 1}/${retries} for saving blueprint...`);
        await new Promise(r => setTimeout(r, 500 * (i + 1)));
      }
    }
  }

  /**
   * Update generated files (creates a new blueprint version)
   */
  static async updateGeneratedFiles(
    projectId: string,
    files: any[], // generatedFile[]
    retries: number = 2
  ): Promise<void> {
    // 1. Get current project state
    const project = await this.getProject(projectId);

    // 2. Prepare updated data
    const currentBlueprint = project.blueprint;
    const currentGenerated = project.generated_files;

    const newGeneratedProject = {
      ...currentGenerated,
      files: files,
      summary: {
        ...currentGenerated.summary,
        totalFiles: files.length
      }
    };

    // 3. Save as new version
    await this.saveGeneratedBlueprint(
      projectId,
      currentBlueprint,
      newGeneratedProject,
      'Code Update'
    );
  }

  /**
   * Create a generation step
   */
  static async createStep(
    projectId: string,
    stepName: string,
    stepType?: string,
    metadata?: any
  ): Promise<ProjectGenerationStep> {
    try {
      const { data, error } = await supabase
        .from('project_generation_steps')
        .insert({
          project_id: projectId,
          step_name: stepName,
          step_type: stepType,
          metadata: metadata,
          status: 'pending',
        })
        .select()
        .single();

      if (error) {
        console.error("Supabase error in createStep:", error);
        throw error;
      }
      return data;
    } catch (error) {
      console.warn("Failed to create step, using fallback:", error);
      return {
        id: 'temp-' + Math.random().toString(36).substring(2, 9),
        project_id: projectId,
        step_name: stepName,
        status: 'pending',
        created_at: new Date().toISOString()
      };
    }
  }

  /**
   * Get the next pending step for a project
   */
  static async getPendingStep(projectId: string): Promise<ProjectGenerationStep | null> {
    const { data, error } = await supabase
      .from('project_generation_steps')
      .select('*')
      .eq('project_id', projectId)
      .eq('status', 'pending')
      .order('created_at', { ascending: true })
      .limit(1)
      .single();

    if (error) return null;
    return data;
  }

  /**
   * Clear all steps for a project
   */
  static async clearSteps(projectId: string): Promise<void> {
    await supabase
      .from('project_generation_steps')
      .delete()
      .eq('project_id', projectId);
  }

  /**
   * Update step status
   */
  static async updateStep(
    stepId: string,
    status: 'pending' | 'in-progress' | 'completed' | 'failed',
    details?: string
  ): Promise<void> {
    const update: any = {
      status,
      started_at: status === 'in-progress' ? new Date().toISOString() : undefined,
      completed_at: status === 'completed' || status === 'failed' ? new Date().toISOString() : undefined,
    };

    if (details) update.details = details;

    // Remove undefined values
    Object.keys(update).forEach(k => update[k] === undefined && delete update[k]);

    const { error } = await supabase
      .from('project_generation_steps')
      .update(update)
      .eq('id', stepId);

    if (error) console.error("Failed to update step:", error);
  }

  /**
   * Get all steps for a project
   */
  static async getProjectSteps(projectId: string, retries: number = 2): Promise<ProjectGenerationStep[]> {
    for (let i = 0; i <= retries; i++) {
      try {
        const { data, error } = await supabase
          .from('project_generation_steps')
          .select('*')
          .eq('project_id', projectId)
          .order('created_at', { ascending: true });

        if (error) throw error;
        return data;
      } catch (error) {
        if (i === retries) {
          console.warn("Failed to fetch steps after retries:", error);
          return [];
        }
        console.warn(`Retry ${i + 1}/${retries} for fetching steps...`);
        await new Promise(r => setTimeout(r, 500 * (i + 1)));
      }
    }
    return [];
  }

  /**
   * Get generation progress and steps
   */
  static async getGenerationProgress(projectId: string): Promise<{ steps: ProjectGenerationStep[], progress: number }> {
    const steps = await this.getProjectSteps(projectId);
    const completedCount = steps.filter(s => s.status === 'completed').length;
    const progress = steps.length > 0 ? Math.round((completedCount / steps.length) * 100) : 0;

    return {
      steps,
      progress
    };
  }

  /**
   * Helper to map normalized data to legacy frontend structure
   */
  private static mapToLegacy(project: any): GeneratedProjectRecord {
    const latestBlueprint = project.blueprints?.[0] || {};
    // Parse JSONs
    let parsedBlueprint: Blueprint | any = {};
    let parsedFiles: GeneratedProject | any = { name: '', files: [], summary: { totalFiles: 0, technologies: [], apiEndpoints: 0, components: 0 } };

    try {
      if (latestBlueprint.content) parsedBlueprint = JSON.parse(latestBlueprint.content);
      if (latestBlueprint.code_json) parsedFiles = JSON.parse(latestBlueprint.code_json);
    } catch (e) {
      console.error("Failed to parse blueprint JSON", e);
    }

    return {
      ...project,
      project_name: project.name,
      project_slug: project.slug || '',
      blueprint: parsedBlueprint,
      generated_files: parsedFiles,
      current_step: project.status, // approximate mapping
      error_message: null,
      api_endpoints: parsedFiles.summary?.apiEndpoints || 0,
      components: parsedFiles.summary?.components || 0,
      completed_at: project.updated_at
    };
  }
}
