import { NextRequest, NextResponse } from 'next/server';
import { Octokit } from '@octokit/rest';

export async function POST(request: NextRequest) {
  try {
    const { blueprint, token, repoName, isPrivate } = await request.json();

    if (!blueprint || !token || !repoName) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    const octokit = new Octokit({ auth: token });

    // Create repository
    const { data: repo } = await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      description: `Project blueprint: ${blueprint.vibe}`,
      private: isPrivate,
      auto_init: true,
    });

    // Create README.md with blueprint content
    await octokit.repos.createOrUpdateFileContents({
      owner: repo.owner.login,
      repo: repo.name,
      path: 'BLUEPRINT.md',
      message: 'Add project blueprint',
      content: Buffer.from(blueprint.blueprint).toString('base64'),
    });

    // Create basic project structure files
    const projectFiles = [
      {
        path: 'README.md',
        content: `# ${blueprint.vibe}\n\nGenerated by VibeCode Mentor\n\nSee [BLUEPRINT.md](./BLUEPRINT.md) for the complete project blueprint.`,
      },
      {
        path: '.gitignore',
        content: `node_modules/\n.env\n.env.local\n.next/\ndist/\nbuild/\n.DS_Store\n*.log`,
      },
      {
        path: 'package.json',
        content: JSON.stringify(
          {
            name: repoName.toLowerCase().replace(/[^a-z0-9-]/g, '-'),
            version: '0.1.0',
            description: blueprint.vibe,
            scripts: {
              dev: 'echo "Setup your development command"',
              build: 'echo "Setup your build command"',
              start: 'echo "Setup your start command"',
            },
          },
          null,
          2
        ),
      },
    ];

    for (const file of projectFiles) {
      await octokit.repos.createOrUpdateFileContents({
        owner: repo.owner.login,
        repo: repo.name,
        path: file.path,
        message: `Add ${file.path}`,
        content: Buffer.from(file.content).toString('base64'),
      });
    }

    return NextResponse.json({
      success: true,
      repoUrl: repo.html_url,
      cloneUrl: repo.clone_url,
    });
  } catch (error: any) {
    console.error('GitHub repo creation error:', error);
    
    if (error.status === 401) {
      return NextResponse.json(
        { error: 'Invalid GitHub token', message: 'Please check your GitHub personal access token' },
        { status: 401 }
      );
    }
    
    if (error.status === 422) {
      return NextResponse.json(
        { error: 'Repository name already exists', message: 'Please choose a different name' },
        { status: 422 }
      );
    }

    return NextResponse.json(
      { error: 'Failed to create repository', message: error.message },
      { status: 500 }
    );
  }
}
