
import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/authOptions';
import { ProjectDatabase } from '@/lib/db/projects';
import { GitHubTokenDatabase } from '@/lib/db/github';
import { pushProjectToGithub } from '@/lib/github/repository';
import { GeneratedFile } from '@/lib/code-generator/types';

export async function POST(req: NextRequest) {
    try {
        const session = await getServerSession(authOptions);
        if (!session?.user?.id) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const { projectId } = await req.json();
        if (!projectId) {
            return NextResponse.json({ error: 'Project ID is required' }, { status: 400 });
        }

        // 1. Get Project Data
        const project = await ProjectDatabase.getProject(projectId);
        if (!project) {
            return NextResponse.json({ error: 'Project not found' }, { status: 404 });
        }

        if (!project.generated_files || !project.generated_files.files) {
            return NextResponse.json({ error: 'No code generated for this project yet.' }, { status: 400 });
        }

        // 2. Get GitHub Token
        const token = await GitHubTokenDatabase.getToken(session.user.id);
        if (!token) {
            return NextResponse.json({ error: 'GitHub not connected', code: 'GITHUB_AUTH_REQUIRED' }, { status: 401 });
        }

        // 3. Prepare Files
        const files = project.generated_files.files as GeneratedFile[];

        // 4. Push to GitHub (Create or Update)
        // Note: pushProjectToGithub in lib/github/repository.ts currently handles creation.
        // If we want to support updates to existing repos, we might need logic to check if repo exists.
        // But pushProjectToGithub implementation:
        // - createRepository (fails if exists?)
        // Let's check repository.ts behavior.
        // It calls this.octokit.repos.createForAuthenticatedUser. This usually fails if name exists.

        // We should refine this logic. Ideally we check if project.github_repo_id exists.
        // But pushProjectToGithub is a high-level helper. Let's see if we can use it or need to be more granular.

        let repoUrl = project.github_url;
        let repoName = project.github_url ? project.github_url.split('/').pop() : project.name.toLowerCase().replace(/[^a-z0-9]/g, '-');

        try {
            if (project.github_repo_id && project.github_url) {
                // Update existing repo
                // We need to instantiate GitHubRepository manually here to push to existing
                const { GitHubRepository } = await import('@/lib/github/repository');
                const github = new GitHubRepository(token.access_token);

                const owner = project.github_url.split('/')[3];
                const repo = project.github_url.split('/')[4];

                await github.pushFiles(owner, repo, files, 'Update from VibeCode Mentor');
                console.log(`Updated existing repo: ${owner}/${repo}`);
            } else {
                // Create new repo
                // Ensure unique name if collision?
                // For now, let's try pushProjectToGithub
                const result = await pushProjectToGithub(
                    token.access_token,
                    repoName || 'vibecode-app',
                    project.description || 'Generated by VibeCode Mentor',
                    files
                );

                repoUrl = result.repoUrl;

                // Update Project with GitHub info
                await ProjectDatabase.updateProjectGithubUrl(projectId, repoUrl, result.repoId);
            }
        } catch (err: any) {
            console.error("GitHub Sync Error:", err);
            // If error is "Repository already exists", we should try to attach to it or rename.
            return NextResponse.json({ error: `GitHub Sync Failed: ${err.message}` }, { status: 500 });
        }

        // Update Project in DB (We need to ensure this works)
        // I will use a direct supabase call here if ProjectDatabase doesn't support it to be safe.
        // But better to use the abstraction.

        // Log Deployment
        const { DeploymentDatabase } = await import('@/lib/db/deployments');
        await DeploymentDatabase.createDeployment({
            project_id: projectId,
            provider: 'github',
            url: repoUrl || '',
            status: 'success'
        });

        return NextResponse.json({
            success: true,
            github_url: repoUrl
        });

    } catch (error) {
        console.error('Deploy API Error:', error);
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}
