/**
 * Scaffold Generator Library
 * Generates project scaffolds from blueprints
 */

import JSZip from 'jszip';

interface Blueprint {
  title: string;
  summary: string;
  scope: string[];
  stack: any;
  systemDesign?: any;
  folderStructure: string[];
  tasks: any[];
  filespec?: any[];
}

/**
 * Generate package.json content
 */
function generatePackageJson(blueprint: Blueprint): string {
  const projectName = blueprint.title.toLowerCase().replace(/[^a-z0-9]/g, '-');
  
  return JSON.stringify({
    name: projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    },
    dependencies: {
      'next': '^14.2.0',
      'react': '^18.3.0',
      'react-dom': '^18.3.0',
      'typescript': '^5.0.0',
    },
    devDependencies: {
      '@types/node': '^20.0.0',
      '@types/react': '^18.0.0',
      '@types/react-dom': '^18.0.0',
      'autoprefixer': '^10.0.0',
      'postcss': '^8.0.0',
      'tailwindcss': '^3.0.0',
      'eslint': '^8.0.0',
      'eslint-config-next': '^14.0.0',
    },
  }, null, 2);
}

/**
 * Generate tsconfig.json content
 */
function generateTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2017',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      forceConsistentCasingInFileNames: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [
        {
          name: 'next',
        },
      ],
      paths: {
        '@/*': ['./*'],
      },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  }, null, 2);
}

/**
 * Generate README.md content
 */
function generateReadme(blueprint: Blueprint): string {
  return `# ${blueprint.title}

${blueprint.summary}

## Getting Started

### Prerequisites

- Node.js 18+ installed
- npm or yarn package manager

### Installation

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Run the development server:
\`\`\`bash
npm run dev
\`\`\`

3. Open [http://localhost:3000](http://localhost:3000) in your browser

## Tech Stack

${Object.entries(blueprint.stack).map(([key, value]) => `- **${key}**: ${value}`).join('\n')}

## Project Scope

${blueprint.scope.map((item, idx) => `${idx + 1}. ${item}`).join('\n')}

## Development Tasks

${blueprint.tasks.map((task: any) => `
### ${task.title}
${task.description}
- Estimated Hours: ${task.estimateHours}
- Difficulty: ${task.difficulty}/10
- Sprint: ${task.sprint}
`).join('\n')}

## Deployment

### Deploy to Vercel

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new)

1. Push your code to GitHub
2. Go to [vercel.com](https://vercel.com) and sign in
3. Click "New Project" and import your repository
4. Configure environment variables (if any)
5. Click "Deploy"

## License

MIT

---

Generated with ❤️ by [VibeCode Mentor](https://vibecode-mentor.vercel.app)
`;
}

/**
 * Generate .gitignore content
 */
function generateGitignore(): string {
  return `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local
.env

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
`;
}

/**
 * Generate tailwind.config.ts content
 */
function generateTailwindConfig(): string {
  return `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
      },
    },
  },
  plugins: [],
}
export default config
`;
}

/**
 * Generate next.config.mjs content
 */
function generateNextConfig(): string {
  return `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

export default nextConfig
`;
}

/**
 * Generate app layout file
 */
function generateAppLayout(): string {
  return `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by VibeCode Mentor',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`;
}

/**
 * Generate app page file
 */
function generateAppPage(blueprint: Blueprint): string {
  return `export default function Home() {
  return (
    <main className="min-h-screen p-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-4">
          ${blueprint.title}
        </h1>
        <p className="text-gray-600 mb-8">
          ${blueprint.summary}
        </p>
        
        <div className="grid gap-4">
          {/* Add your components here */}
        </div>
      </div>
    </main>
  )
}
`;
}

/**
 * Generate globals.css content
 */
function generateGlobalsCss(): string {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: Arial, Helvetica, sans-serif;
}
`;
}

/**
 * Generate .env.example file
 */
function generateEnvExample(): string {
  return `# Environment Variables Template
# Copy this file to .env.local and fill in your values

# API Keys
# Add your API keys here

# Database
# Add your database connection strings here
`;
}

/**
 * Generate project scaffold as ZIP
 */
export async function generateScaffoldZip(blueprint: Blueprint): Promise<Buffer> {
  const zip = new JSZip();

  // Root files
  zip.file('package.json', generatePackageJson(blueprint));
  zip.file('tsconfig.json', generateTsConfig());
  zip.file('README.md', generateReadme(blueprint));
  zip.file('.gitignore', generateGitignore());
  zip.file('tailwind.config.ts', generateTailwindConfig());
  zip.file('next.config.mjs', generateNextConfig());
  zip.file('.env.example', generateEnvExample());

  // App directory
  zip.file('app/layout.tsx', generateAppLayout());
  zip.file('app/page.tsx', generateAppPage(blueprint));
  zip.file('app/globals.css', generateGlobalsCss());

  // Components directory
  zip.file('components/.gitkeep', '');

  // Lib directory
  zip.file('lib/.gitkeep', '');

  // Types directory
  zip.file('types/.gitkeep', '');

  // Public directory
  zip.file('public/.gitkeep', '');

  // Generate additional files from filespec if available
  if (blueprint.filespec && blueprint.filespec.length > 0) {
    for (const file of blueprint.filespec) {
      const placeholder = `// ${file.purpose || file.path}\n// TODO: Implement this file\n\nexport {};\n`;
      zip.file(file.path, placeholder);
    }
  }

  // Generate the ZIP file
  const zipBuffer = await zip.generateAsync({ 
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 }
  });

  return zipBuffer;
}

/**
 * Get file structure as array
 */
export function getScaffoldStructure(blueprint: Blueprint): string[] {
  const structure = [
    'package.json',
    'tsconfig.json',
    'README.md',
    '.gitignore',
    'tailwind.config.ts',
    'next.config.mjs',
    '.env.example',
    'app/',
    'app/layout.tsx',
    'app/page.tsx',
    'app/globals.css',
    'components/',
    'lib/',
    'types/',
    'public/',
  ];

  if (blueprint.filespec && blueprint.filespec.length > 0) {
    structure.push(...blueprint.filespec.map((f: any) => f.path));
  }

  return structure.sort();
}
