export interface Template {
  id: string;
  name: string;
  description: string;
  category: 'web' | 'mobile' | 'saas' | 'ecommerce' | 'ai' | 'other' | 'devtools';
  icon: string;
  prompt: string;
  tags: string[];
  complexity: 'beginner' | 'intermediate' | 'advanced';
  estimatedTime: string;
  isPro: boolean;
}

export const templates: Template[] = [
  {
    id: 'ecommerce-full',
    name: 'E-Commerce Platform',
    description: 'Full-featured online store with payments, inventory, and admin panel',
    category: 'ecommerce',
    icon: '🛒',
    prompt: 'Build a complete e-commerce platform with Next.js 14, Stripe payments, Prisma with PostgreSQL, real-time inventory tracking, admin dashboard with analytics, email notifications, product search with filters, shopping cart, wishlist, order management, and mobile-responsive design.',
    tags: ['Next.js', 'Stripe', 'PostgreSQL', 'Prisma', 'Tailwind'],
    complexity: 'advanced',
    estimatedTime: '4-6 weeks',
    isPro: false,
  },
  {
    id: 'saas-starter',
    name: 'SaaS Starter Kit',
    description: 'Production-ready SaaS boilerplate with auth, billing, and multi-tenancy',
    category: 'saas',
    icon: '🚀',
    prompt: 'Create a SaaS starter kit with Next.js 14 App Router, Clerk authentication, Stripe subscriptions with multiple tiers, multi-tenant architecture with team workspaces, role-based access control (RBAC), PostgreSQL with Prisma, admin dashboard, usage analytics, API rate limiting, webhook handlers, email notifications with Resend, and comprehensive testing setup.',
    tags: ['SaaS', 'Auth', 'Stripe', 'Multi-tenant', 'RBAC'],
    complexity: 'advanced',
    estimatedTime: '6-8 weeks',
    isPro: true,
  },
  {
    id: 'ai-chatbot',
    name: 'AI Chatbot Platform',
    description: 'Intelligent chatbot with conversation memory and RAG',
    category: 'ai',
    icon: '🤖',
    prompt: 'Build an AI chatbot platform using Next.js 14, OpenAI GPT-4, Pinecone vector database for RAG (Retrieval Augmented Generation), conversation history with Redis, streaming responses, file upload for context, customizable system prompts, chat analytics, API for integration, and beautiful chat UI with markdown support.',
    tags: ['AI', 'OpenAI', 'RAG', 'Pinecone', 'Streaming'],
    complexity: 'advanced',
    estimatedTime: '3-4 weeks',
    isPro: true,
  },
  {
    id: 'mobile-social',
    name: 'Social Media App',
    description: 'Mobile-first social network with real-time features',
    category: 'mobile',
    icon: '📱',
    prompt: 'Create a mobile-first social media app with React Native or Next.js PWA, real-time posts and comments using WebSockets, image/video upload with AWS S3, user profiles and follow system, likes and reactions, notifications (push for mobile), infinite scroll feed, stories feature, direct messaging, and content moderation.',
    tags: ['React Native', 'WebSockets', 'S3', 'Real-time'],
    complexity: 'advanced',
    estimatedTime: '5-7 weeks',
    isPro: false,
  },
  {
    id: 'task-manager',
    name: 'Task Management Tool',
    description: 'Collaborative project management with Kanban boards',
    category: 'saas',
    icon: '✅',
    prompt: 'Build a task management application like Trello/Asana with Next.js 14, drag-and-drop Kanban boards using dnd-kit, real-time collaboration with WebSockets, task assignments and due dates, file attachments, comments and activity feed, project templates, calendar view, time tracking, team workspaces, and mobile-responsive design.',
    tags: ['Kanban', 'Real-time', 'Collaboration', 'DnD'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'blog-cms',
    name: 'Blog & CMS Platform',
    description: 'SEO-optimized blog with headless CMS',
    category: 'web',
    icon: '📝',
    prompt: 'Create a blog and CMS platform with Next.js 14 App Router, MDX support for rich content, Contentful or Sanity as headless CMS, SEO optimization with metadata, sitemap generation, RSS feed, author profiles, categories and tags, search functionality, comments system, analytics integration, newsletter signup, and beautiful typography.',
    tags: ['Blog', 'CMS', 'MDX', 'SEO', 'Contentful'],
    complexity: 'intermediate',
    estimatedTime: '2-3 weeks',
    isPro: false,
  },
  {
    id: 'video-streaming',
    name: 'Video Streaming Platform',
    description: 'YouTube-like platform with live streaming',
    category: 'web',
    icon: '🎥',
    prompt: 'Build a video streaming platform similar to YouTube with Next.js 14, video upload and transcoding using AWS MediaConvert or Mux, HLS/DASH adaptive streaming, live streaming with RTMP, video player with custom controls, playlists, subscriptions, comments, likes/dislikes, view analytics, recommendations algorithm, and monetization options.',
    tags: ['Video', 'Streaming', 'AWS', 'Mux', 'RTMP'],
    complexity: 'advanced',
    estimatedTime: '6-8 weeks',
    isPro: true,
  },
  {
    id: 'fitness-tracker',
    name: 'Fitness Tracker App',
    description: 'Health and workout tracking with charts',
    category: 'mobile',
    icon: '💪',
    prompt: 'Create a fitness tracking app with Next.js PWA or React Native, workout logging with exercise library, progress tracking with charts using Recharts, nutrition tracking with calorie counter, goal setting and achievements, body measurements tracking, workout plans and routines, rest timer, social features to share progress, and Apple Health/Google Fit integration.',
    tags: ['Fitness', 'PWA', 'Charts', 'Mobile', 'Health'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'invoice-generator',
    name: 'Invoice & Billing System',
    description: 'Professional invoicing with payment tracking',
    category: 'saas',
    icon: '💰',
    prompt: 'Build an invoice and billing system with Next.js 14, PDF generation for invoices using React-PDF, client management, recurring invoices, payment tracking with Stripe integration, expense tracking, financial reports and analytics, multi-currency support, tax calculations, email reminders for overdue invoices, and mobile-responsive design.',
    tags: ['Invoicing', 'PDF', 'Stripe', 'Finance', 'Reports'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'learning-platform',
    name: 'Online Learning Platform',
    description: 'LMS with courses, quizzes, and certificates',
    category: 'saas',
    icon: '🎓',
    prompt: 'Create an online learning management system (LMS) with Next.js 14, course creation and management, video lessons with progress tracking, quizzes and assessments, certificates generation, student dashboard with enrolled courses, instructor dashboard with analytics, discussion forums, live classes with Zoom integration, payment integration for paid courses, and course recommendations.',
    tags: ['LMS', 'Education', 'Video', 'Certificates', 'Quizzes'],
    complexity: 'advanced',
    estimatedTime: '5-6 weeks',
    isPro: true,
  },
  {
    id: 'api-backend',
    name: 'REST API Backend',
    description: 'Production-ready REST API with authentication and docs',
    category: 'devtools',
    icon: '⚡',
    prompt: 'Build a production-ready REST API backend using Node.js with Express or Fastify, PostgreSQL database with Prisma ORM, JWT authentication with refresh tokens, role-based authorization, API versioning, request validation with Zod, rate limiting, CORS configuration, comprehensive error handling, API documentation with Swagger/OpenAPI, automated testing with Jest, Docker containerization, and deployment guides for AWS/Vercel.',
    tags: ['API', 'Node.js', 'Express', 'PostgreSQL', 'JWT', 'Docker'],
    complexity: 'intermediate',
    estimatedTime: '2-3 weeks',
    isPro: false,
  },
  {
    id: 'cli-tool',
    name: 'CLI Development Tool',
    description: 'Command-line tool with interactive prompts',
    category: 'devtools',
    icon: '🔧',
    prompt: 'Create a professional CLI tool using Node.js with Commander.js or Yargs, interactive prompts with Inquirer.js, colorful terminal output with Chalk, progress bars and spinners with Ora, file operations and templating, configuration management, automatic update checks, comprehensive help documentation, error handling, unit testing with Jest, and npm publishing setup. Include examples like code scaffolding, project initialization, or automation tasks.',
    tags: ['CLI', 'Node.js', 'Commander', 'Terminal', 'NPM'],
    complexity: 'beginner',
    estimatedTime: '1-2 weeks',
    isPro: false,
  },
  {
    id: 'chrome-extension',
    name: 'Chrome Extension',
    description: 'Browser extension with React and Manifest V3',
    category: 'devtools',
    icon: '🧩',
    prompt: 'Build a modern Chrome extension using React 18, TypeScript, Manifest V3, Chrome Extension API, background service workers, content scripts for page interaction, popup UI with Tailwind CSS, options page for settings, storage management with chrome.storage, message passing between components, browser action and context menus, webRequest API for network inspection, and build setup with Vite or Webpack. Include extension icons and publishing guide.',
    tags: ['Chrome', 'Extension', 'React', 'TypeScript', 'Manifest V3'],
    complexity: 'intermediate',
    estimatedTime: '2-3 weeks',
    isPro: false,
  },
  {
    id: 'devops-dashboard',
    name: 'DevOps Monitoring Dashboard',
    description: 'Real-time system monitoring and alerting platform',
    category: 'devtools',
    icon: '📊',
    prompt: 'Create a DevOps monitoring dashboard with Next.js 14, real-time metrics visualization using Recharts, server health monitoring, Docker container status, CI/CD pipeline tracking, log aggregation and searching, alert system with email/Slack notifications, custom metric dashboards, historical data analysis, multi-server support, Prometheus/Grafana integration, incident management, and mobile-responsive design for on-call engineers.',
    tags: ['DevOps', 'Monitoring', 'Docker', 'CI/CD', 'Grafana'],
    complexity: 'advanced',
    estimatedTime: '4-5 weeks',
    isPro: true,
  },
  {
    id: 'markdown-editor',
    name: 'Markdown Editor & Preview',
    description: 'Real-time markdown editor for developers',
    category: 'devtools',
    icon: '📝',
    prompt: 'Build a powerful markdown editor with Next.js 14, split-pane live preview, syntax highlighting with CodeMirror or Monaco Editor, GitHub Flavored Markdown support, table of contents generation, export to PDF/HTML, code block syntax highlighting, diagram support with Mermaid, math equations with KaTeX, keyboard shortcuts, auto-save with localStorage, cloud sync for signed-in users, themes (light/dark/custom), and PWA for offline editing.',
    tags: ['Markdown', 'Editor', 'CodeMirror', 'PWA', 'Export'],
    complexity: 'intermediate',
    estimatedTime: '2-3 weeks',
    isPro: false,
  },
  {
    id: 'code-snippet-manager',
    name: 'Code Snippet Manager',
    description: 'Organize and share code snippets with teams',
    category: 'devtools',
    icon: '💾',
    prompt: 'Create a code snippet manager with Next.js 14, syntax highlighting for 100+ languages, organize snippets with tags and collections, search with fuzzy matching, version history for snippets, share snippets via links, team collaboration with shared collections, VS Code extension integration, CLI for quick access, snippet templates, code playground for testing, export/import functionality, Gist sync, and browser extension for quick saving.',
    tags: ['Snippets', 'Code', 'VS Code', 'Collaboration', 'Search'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: true,
  },
  {
    id: 'portfolio-generator',
    name: 'Developer Portfolio Builder',
    description: 'Beautiful portfolio site generator for developers',
    category: 'web',
    icon: '🎨',
    prompt: 'Build a developer portfolio generator with Next.js 14, customizable themes (10+ professional designs), GitHub integration to fetch projects automatically, blog with MDX support, resume/CV section, skills visualization, project showcase with live demos, contact form with email integration, SEO optimization, analytics dashboard, dark/light mode, mobile responsive, one-click deploy to Vercel/Netlify, and custom domain support.',
    tags: ['Portfolio', 'GitHub', 'MDX', 'SEO', 'Resume'],
    complexity: 'intermediate',
    estimatedTime: '2-3 weeks',
    isPro: false,
  },
  {
    id: 'webhook-tester',
    name: 'Webhook Testing Tool',
    description: 'Test and debug webhooks in real-time',
    category: 'devtools',
    icon: '🔔',
    prompt: 'Create a webhook testing tool with Next.js 14 and Node.js, unique URL generation for each user, real-time webhook capture with WebSockets, request inspector showing headers/body/query params, webhook forwarding to local development, request history and search, webhook replay functionality, custom response configuration, authentication testing (HMAC, OAuth), delay simulation, batch webhook generation, export request logs, and team collaboration features.',
    tags: ['Webhooks', 'Testing', 'WebSockets', 'API', 'Dev Tools'],
    complexity: 'advanced',
    estimatedTime: '3-4 weeks',
    isPro: true,
  },
  {
    id: 'landing-page-builder',
    name: 'Landing Page Builder',
    description: 'No-code landing page creator for makers',
    category: 'web',
    icon: '🚀',
    prompt: 'Build a no-code landing page builder with Next.js 14, drag-and-drop page editor, pre-built sections (hero, features, pricing, testimonials, FAQ, CTA), customizable components, responsive design controls, color scheme customization, typography settings, image optimization, form builder with integrations (Mailchimp, ConvertKit), analytics tracking, A/B testing, SEO settings, custom domain support, and one-click publishing.',
    tags: ['No-Code', 'Landing Page', 'Drag-Drop', 'Marketing', 'SEO'],
    complexity: 'advanced',
    estimatedTime: '5-6 weeks',
    isPro: true,
  },
];

export const getTemplatesByCategory = (category: Template['category']) => {
  return templates.filter(t => t.category === category);
};

export const getFreeTemplates = () => {
  return templates.filter(t => !t.isPro);
};

export const getProTemplates = () => {
  return templates.filter(t => t.isPro);
};

export const getTemplateById = (id: string) => {
  return templates.find(t => t.id === id);
};
