export interface Template {
  id: string;
  name: string;
  description: string;
  category: 'web' | 'mobile' | 'saas' | 'ecommerce' | 'ai' | 'other' | 'devtools';
  icon: string;
  prompt: string;
  tags: string[];
  complexity: 'beginner' | 'intermediate' | 'advanced';
  estimatedTime: string;
  isPro: boolean;
}

export const templates: Template[] = [
  {
    id: 'ecommerce-full',
    name: 'E-Commerce Platform',
    description: 'Full-featured online store with payments, inventory, and admin panel',
    category: 'ecommerce',
    icon: '🛒',
    prompt: 'Build a complete e-commerce platform with Next.js 14, Stripe payments, Prisma with PostgreSQL, real-time inventory tracking, admin dashboard with analytics, email notifications, product search with filters, shopping cart, wishlist, order management, and mobile-responsive design.',
    tags: ['Next.js', 'Stripe', 'PostgreSQL', 'Prisma', 'Tailwind'],
    complexity: 'advanced',
    estimatedTime: '4-6 weeks',
    isPro: false,
  },
  {
    id: 'saas-starter',
    name: 'SaaS Starter Kit',
    description: 'Production-ready SaaS boilerplate with auth, billing, and multi-tenancy',
    category: 'saas',
    icon: '🚀',
    prompt: 'Create a SaaS starter kit with Next.js 14 App Router, Clerk authentication, Stripe subscriptions with multiple tiers, multi-tenant architecture with team workspaces, role-based access control (RBAC), PostgreSQL with Prisma, admin dashboard, usage analytics, API rate limiting, webhook handlers, email notifications with Resend, and comprehensive testing setup.',
    tags: ['SaaS', 'Auth', 'Stripe', 'Multi-tenant', 'RBAC'],
    complexity: 'advanced',
    estimatedTime: '6-8 weeks',
    isPro: true,
  },
  {
    id: 'ai-chatbot',
    name: 'AI Chatbot Platform',
    description: 'Intelligent chatbot with conversation memory and RAG',
    category: 'ai',
    icon: '🤖',
    prompt: 'Build an AI chatbot platform using Next.js 14, OpenAI GPT-4, Pinecone vector database for RAG (Retrieval Augmented Generation), conversation history with Redis, streaming responses, file upload for context, customizable system prompts, chat analytics, API for integration, and beautiful chat UI with markdown support.',
    tags: ['AI', 'OpenAI', 'RAG', 'Pinecone', 'Streaming'],
    complexity: 'advanced',
    estimatedTime: '3-4 weeks',
    isPro: true,
  },
  {
    id: 'mobile-social',
    name: 'Social Media App',
    description: 'Mobile-first social network with real-time features',
    category: 'mobile',
    icon: '📱',
    prompt: 'Create a mobile-first social media app with React Native or Next.js PWA, real-time posts and comments using WebSockets, image/video upload with AWS S3, user profiles and follow system, likes and reactions, notifications (push for mobile), infinite scroll feed, stories feature, direct messaging, and content moderation.',
    tags: ['React Native', 'WebSockets', 'S3', 'Real-time'],
    complexity: 'advanced',
    estimatedTime: '5-7 weeks',
    isPro: false,
  },
  {
    id: 'task-manager',
    name: 'Task Management Tool',
    description: 'Collaborative project management with Kanban boards',
    category: 'saas',
    icon: '✅',
    prompt: 'Build a task management application like Trello/Asana with Next.js 14, drag-and-drop Kanban boards using dnd-kit, real-time collaboration with WebSockets, task assignments and due dates, file attachments, comments and activity feed, project templates, calendar view, time tracking, team workspaces, and mobile-responsive design.',
    tags: ['Kanban', 'Real-time', 'Collaboration', 'DnD'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'blog-cms',
    name: 'Blog & CMS Platform',
    description: 'SEO-optimized blog with headless CMS',
    category: 'web',
    icon: '📝',
    prompt: 'Create a blog and CMS platform with Next.js 14 App Router, MDX support for rich content, Contentful or Sanity as headless CMS, SEO optimization with metadata, sitemap generation, RSS feed, author profiles, categories and tags, search functionality, comments system, analytics integration, newsletter signup, and beautiful typography.',
    tags: ['Blog', 'CMS', 'MDX', 'SEO', 'Contentful'],
    complexity: 'intermediate',
    estimatedTime: '2-3 weeks',
    isPro: false,
  },
  {
    id: 'video-streaming',
    name: 'Video Streaming Platform',
    description: 'YouTube-like platform with live streaming',
    category: 'web',
    icon: '🎥',
    prompt: 'Build a video streaming platform similar to YouTube with Next.js 14, video upload and transcoding using AWS MediaConvert or Mux, HLS/DASH adaptive streaming, live streaming with RTMP, video player with custom controls, playlists, subscriptions, comments, likes/dislikes, view analytics, recommendations algorithm, and monetization options.',
    tags: ['Video', 'Streaming', 'AWS', 'Mux', 'RTMP'],
    complexity: 'advanced',
    estimatedTime: '6-8 weeks',
    isPro: true,
  },
  {
    id: 'fitness-tracker',
    name: 'Fitness Tracker App',
    description: 'Health and workout tracking with charts',
    category: 'mobile',
    icon: '💪',
    prompt: 'Create a fitness tracking app with Next.js PWA or React Native, workout logging with exercise library, progress tracking with charts using Recharts, nutrition tracking with calorie counter, goal setting and achievements, body measurements tracking, workout plans and routines, rest timer, social features to share progress, and Apple Health/Google Fit integration.',
    tags: ['Fitness', 'PWA', 'Charts', 'Mobile', 'Health'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'invoice-generator',
    name: 'Invoice & Billing System',
    description: 'Professional invoicing with payment tracking',
    category: 'saas',
    icon: '💰',
    prompt: 'Build an invoice and billing system with Next.js 14, PDF generation for invoices using React-PDF, client management, recurring invoices, payment tracking with Stripe integration, expense tracking, financial reports and analytics, multi-currency support, tax calculations, email reminders for overdue invoices, and mobile-responsive design.',
    tags: ['Invoicing', 'PDF', 'Stripe', 'Finance', 'Reports'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'learning-platform',
    name: 'Online Learning Platform',
    description: 'LMS with courses, quizzes, and certificates',
    category: 'saas',
    icon: '🎓',
    prompt: 'Create an online learning management system (LMS) with Next.js 14, course creation and management, video lessons with progress tracking, quizzes and assessments, certificates generation, student dashboard with enrolled courses, instructor dashboard with analytics, discussion forums, live classes with Zoom integration, payment integration for paid courses, and course recommendations.',
    tags: ['LMS', 'Education', 'Video', 'Certificates', 'Quizzes'],
    complexity: 'advanced',
    estimatedTime: '5-6 weeks',
    isPro: true,
  },
  {
    id: 'api-backend',
    name: 'REST API Backend',
    description: 'Production-ready REST API with authentication and docs',
    category: 'devtools',
    icon: '⚡',
    prompt: 'Build a production-ready REST API backend using Node.js with Express or Fastify, PostgreSQL database with Prisma ORM, JWT authentication with refresh tokens, role-based authorization, API versioning, request validation with Zod, rate limiting, CORS configuration, comprehensive error handling, API documentation with Swagger/OpenAPI, automated testing with Jest, Docker containerization, and deployment guides for AWS/Vercel.',
    tags: ['API', 'Node.js', 'Express', 'PostgreSQL', 'JWT', 'Docker'],
    complexity: 'intermediate',
    estimatedTime: '2-3 weeks',
    isPro: false,
  },
  {
    id: 'cli-tool',
    name: 'CLI Development Tool',
    description: 'Command-line tool with interactive prompts',
    category: 'devtools',
    icon: '🔧',
    prompt: 'Create a professional CLI tool using Node.js with Commander.js or Yargs, interactive prompts with Inquirer.js, colorful terminal output with Chalk, progress bars and spinners with Ora, file operations and templating, configuration management, automatic update checks, comprehensive help documentation, error handling, unit testing with Jest, and npm publishing setup. Include examples like code scaffolding, project initialization, or automation tasks.',
    tags: ['CLI', 'Node.js', 'Commander', 'Terminal', 'NPM'],
    complexity: 'beginner',
    estimatedTime: '1-2 weeks',
    isPro: false,
  },
  {
    id: 'chrome-extension',
    name: 'Chrome Extension',
    description: 'Browser extension with React and Manifest V3',
    category: 'devtools',
    icon: '🧩',
    prompt: 'Build a modern Chrome extension using React 18, TypeScript, Manifest V3, Chrome Extension API, background service workers, content scripts for page interaction, popup UI with Tailwind CSS, options page for settings, storage management with chrome.storage, message passing between components, browser action and context menus, webRequest API for network inspection, and build setup with Vite or Webpack. Include extension icons and publishing guide.',
    tags: ['Chrome', 'Extension', 'React', 'TypeScript', 'Manifest V3'],
    complexity: 'intermediate',
    estimatedTime: '2-3 weeks',
    isPro: false,
  },
  {
    id: 'devops-dashboard',
    name: 'DevOps Monitoring Dashboard',
    description: 'Real-time system monitoring and alerting platform',
    category: 'devtools',
    icon: '📊',
    prompt: 'Create a DevOps monitoring dashboard with Next.js 14, real-time metrics visualization using Recharts, server health monitoring, Docker container status, CI/CD pipeline tracking, log aggregation and searching, alert system with email/Slack notifications, custom metric dashboards, historical data analysis, multi-server support, Prometheus/Grafana integration, incident management, and mobile-responsive design for on-call engineers.',
    tags: ['DevOps', 'Monitoring', 'Docker', 'CI/CD', 'Grafana'],
    complexity: 'advanced',
    estimatedTime: '4-5 weeks',
    isPro: true,
  },
  {
    id: 'markdown-editor',
    name: 'Markdown Editor & Preview',
    description: 'Real-time markdown editor for developers',
    category: 'devtools',
    icon: '📝',
    prompt: 'Build a powerful markdown editor with Next.js 14, split-pane live preview, syntax highlighting with CodeMirror or Monaco Editor, GitHub Flavored Markdown support, table of contents generation, export to PDF/HTML, code block syntax highlighting, diagram support with Mermaid, math equations with KaTeX, keyboard shortcuts, auto-save with localStorage, cloud sync for signed-in users, themes (light/dark/custom), and PWA for offline editing.',
    tags: ['Markdown', 'Editor', 'CodeMirror', 'PWA', 'Export'],
    complexity: 'intermediate',
    estimatedTime: '2-3 weeks',
    isPro: false,
  },
  {
    id: 'code-snippet-manager',
    name: 'Code Snippet Manager',
    description: 'Organize and share code snippets with teams',
    category: 'devtools',
    icon: '💾',
    prompt: 'Create a code snippet manager with Next.js 14, syntax highlighting for 100+ languages, organize snippets with tags and collections, search with fuzzy matching, version history for snippets, share snippets via links, team collaboration with shared collections, VS Code extension integration, CLI for quick access, snippet templates, code playground for testing, export/import functionality, Gist sync, and browser extension for quick saving.',
    tags: ['Snippets', 'Code', 'VS Code', 'Collaboration', 'Search'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: true,
  },
  {
    id: 'portfolio-generator',
    name: 'Developer Portfolio Builder',
    description: 'Beautiful portfolio site generator for developers',
    category: 'web',
    icon: '🎨',
    prompt: 'Build a developer portfolio generator with Next.js 14, customizable themes (10+ professional designs), GitHub integration to fetch projects automatically, blog with MDX support, resume/CV section, skills visualization, project showcase with live demos, contact form with email integration, SEO optimization, analytics dashboard, dark/light mode, mobile responsive, one-click deploy to Vercel/Netlify, and custom domain support.',
    tags: ['Portfolio', 'GitHub', 'MDX', 'SEO', 'Resume'],
    complexity: 'intermediate',
    estimatedTime: '2-3 weeks',
    isPro: false,
  },
  {
    id: 'webhook-tester',
    name: 'Webhook Testing Tool',
    description: 'Test and debug webhooks in real-time',
    category: 'devtools',
    icon: '🔔',
    prompt: 'Create a webhook testing tool with Next.js 14 and Node.js, unique URL generation for each user, real-time webhook capture with WebSockets, request inspector showing headers/body/query params, webhook forwarding to local development, request history and search, webhook replay functionality, custom response configuration, authentication testing (HMAC, OAuth), delay simulation, batch webhook generation, export request logs, and team collaboration features.',
    tags: ['Webhooks', 'Testing', 'WebSockets', 'API', 'Dev Tools'],
    complexity: 'advanced',
    estimatedTime: '3-4 weeks',
    isPro: true,
  },
  {
    id: 'landing-page-builder',
    name: 'Landing Page Builder',
    description: 'No-code landing page creator for makers',
    category: 'web',
    icon: '🚀',
    prompt: 'Build a no-code landing page builder with Next.js 14, drag-and-drop page editor, pre-built sections (hero, features, pricing, testimonials, FAQ, CTA), customizable components, responsive design controls, color scheme customization, typography settings, image optimization, form builder with integrations (Mailchimp, ConvertKit), analytics tracking, A/B testing, SEO settings, custom domain support, and one-click publishing.',
    tags: ['No-Code', 'Landing Page', 'Drag-Drop', 'Marketing', 'SEO'],
    complexity: 'advanced',
    estimatedTime: '5-6 weeks',
    isPro: true,
  },
  {
    id: 'realtime-chat',
    name: 'Real-Time Chat Platform',
    description: 'Scalable chat app with WebSockets and read receipts',
    category: 'web',
    icon: '💬',
    prompt: 'Build a real-time chat platform with Next.js 14, Socket.io for WebSockets, PostgreSQL for message persistence, user presence indicators (online/offline/typing), read receipts, message reactions, group chats with admin controls, file/image sharing, message search, push notifications, end-to-end encryption option, voice/video call integration with WebRTC, and mobile-responsive design.',
    tags: ['Chat', 'WebSockets', 'Socket.io', 'Real-time', 'WebRTC'],
    complexity: 'advanced',
    estimatedTime: '5-6 weeks',
    isPro: true,
  },
  {
    id: 'blockchain-dapp',
    name: 'Web3 DApp Platform',
    description: 'Blockchain application with smart contracts',
    category: 'web',
    icon: '⛓️',
    prompt: 'Create a Web3 decentralized application (DApp) with Next.js 14, Ethereum blockchain integration using ethers.js or web3.js, MetaMask wallet connection, smart contract deployment with Solidity and Hardhat, NFT minting and marketplace, token staking mechanism, DAO voting system, gas optimization, transaction history, Web3 authentication, IPFS for decentralized storage, and testnet/mainnet deployment guides.',
    tags: ['Web3', 'Blockchain', 'Ethereum', 'Smart Contracts', 'NFT'],
    complexity: 'advanced',
    estimatedTime: '6-8 weeks',
    isPro: true,
  },
  {
    id: 'graphql-api',
    name: 'GraphQL API Server',
    description: 'Modern GraphQL API with subscriptions',
    category: 'devtools',
    icon: '🔌',
    prompt: 'Build a production-grade GraphQL API server using Node.js with Apollo Server, PostgreSQL database with Prisma ORM, schema-first design with GraphQL SDL, queries, mutations, and subscriptions for real-time updates, DataLoader for batching and caching, authentication with JWT, authorization with field-level permissions, input validation, pagination with cursor-based approach, GraphQL Playground for testing, comprehensive error handling, rate limiting, monitoring with Apollo Studio, and Docker deployment.',
    tags: ['GraphQL', 'Apollo', 'Node.js', 'Subscriptions', 'Prisma'],
    complexity: 'advanced',
    estimatedTime: '3-4 weeks',
    isPro: true,
  },
  {
    id: 'micro-saas',
    name: 'Micro-SaaS Template',
    description: 'Launch-ready micro-SaaS for niche markets',
    category: 'saas',
    icon: '🎯',
    prompt: 'Create a launch-ready micro-SaaS boilerplate with Next.js 14, Stripe integration for one-time and subscription payments, customer portal for subscription management, usage-based billing and metering, feature flags for gradual rollouts, onboarding flow, email campaigns with Resend, customer feedback widget, affiliate program, referral system, analytics dashboard, lifetime deal support, and comprehensive documentation for customization.',
    tags: ['Micro-SaaS', 'Stripe', 'Billing', 'Onboarding', 'Analytics'],
    complexity: 'intermediate',
    estimatedTime: '4-5 weeks',
    isPro: false,
  },
  {
    id: 'analytics-platform',
    name: 'Analytics \u0026 Tracking Platform',
    description: 'Privacy-focused analytics alternative to Google Analytics',
    category: 'saas',
    icon: '📈',
    prompt: 'Build a privacy-focused analytics platform with Next.js 14, real-time visitor tracking, page views and unique visitors, session recording with rrweb, heatmaps and click tracking, funnel analysis, custom event tracking, UTM parameter tracking, referrer analytics, device and browser stats, geographic data, goal conversions, A/B test tracking, JavaScript tracking snippet, API for data ingestion, GDPR-compliant, and beautiful dashboards with charts.',
    tags: ['Analytics', 'Tracking', 'Privacy', 'Real-time', 'Dashboards'],
    complexity: 'advanced',
    estimatedTime: '5-6 weeks',
    isPro: true,
  },
  {
    id: 'booking-system',
    name: 'Appointment Booking System',
    description: 'Calendar-based booking for services',
    category: 'saas',
    icon: '📅',
    prompt: 'Create an appointment booking system with Next.js 14, calendar UI with availability management, time zone support, service catalog with pricing, online payment with Stripe, automated email/SMS reminders with Twilio, customer management, booking confirmation and cancellation, recurring appointments, waitlist management, staff scheduling, Google Calendar sync, booking widget for embedding, analytics and reports, and multi-location support.',
    tags: ['Bookings', 'Calendar', 'Stripe', 'Twilio', 'Scheduling'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'crm-platform',
    name: 'Customer CRM Platform',
    description: 'Sales pipeline and contact management',
    category: 'saas',
    icon: '👥',
    prompt: 'Build a customer relationship management (CRM) platform with Next.js 14, contact and company management, deal pipeline with drag-and-drop stages, activity timeline and notes, email integration (Gmail/Outlook), task and reminder system, custom fields and tags, sales forecasting, reporting and analytics, team collaboration, email templates, automated workflows, lead scoring, import/export contacts, mobile app, and integrations with Zapier.',
    tags: ['CRM', 'Sales', 'Pipeline', 'Email', 'Automation'],
    complexity: 'advanced',
    estimatedTime: '6-7 weeks',
    isPro: true,
  },
  {
    id: 'serverless-api',
    name: 'Serverless API Gateway',
    description: 'Scalable serverless API with AWS Lambda',
    category: 'devtools',
    icon: '☁️',
    prompt: 'Create a serverless API gateway using AWS Lambda functions, API Gateway for routing, DynamoDB for data storage, S3 for file storage, authentication with Cognito, API key management, request throttling and quotas, Lambda layers for shared code, CloudWatch for logging and monitoring, X-Ray for tracing, deployment with Serverless Framework or AWS SAM, environment variables management, CORS configuration, and cost optimization strategies.',
    tags: ['Serverless', 'AWS Lambda', 'API Gateway', 'DynamoDB', 'Cloud'],
    complexity: 'advanced',
    estimatedTime: '3-4 weeks',
    isPro: true,
  },
  {
    id: 'nft-marketplace',
    name: 'NFT Marketplace',
    description: 'Digital art marketplace with blockchain integration',
    category: 'web',
    icon: '🎨',
    prompt: 'Build an NFT marketplace with Next.js 14, Ethereum blockchain using ethers.js, IPFS for decentralized storage, MetaMask wallet integration, NFT minting interface, marketplace for buying/selling, auction system, creator royalties, collection management, search and filters, user profiles, and responsive design.',
    tags: ['NFT', 'Blockchain', 'Ethereum', 'IPFS', 'MetaMask'],
    complexity: 'advanced',
    estimatedTime: '6-8 weeks',
    isPro: true,
  },
  {
    id: 'food-delivery',
    name: 'Food Delivery App',
    description: 'Restaurant ordering and delivery platform',
    category: 'mobile',
    icon: '🍕',
    prompt: 'Create a food delivery app with React Native or Next.js PWA, restaurant listings with menus, real-time order tracking, GPS integration for delivery, payment processing with Stripe, driver management, rating system, push notifications, order history, and admin dashboard.',
    tags: ['Food Delivery', 'Mobile', 'GPS', 'Stripe', 'Real-time'],
    complexity: 'intermediate',
    estimatedTime: '4-5 weeks',
    isPro: false,
  },
  {
    id: 'dating-app',
    name: 'Dating App',
    description: 'Social dating platform with matching algorithm',
    category: 'mobile',
    icon: '💕',
    prompt: 'Build a dating app with React Native, user profiles with photos, swipe-based matching, chat functionality with WebSockets, location-based matching, premium features, reporting system, video calls, and privacy controls.',
    tags: ['Dating', 'Social', 'WebSockets', 'Video', 'Mobile'],
    complexity: 'advanced',
    estimatedTime: '5-6 weeks',
    isPro: true,
  },
  {
    id: 'job-board',
    name: 'Job Board Platform',
    description: 'Professional job listing and application system',
    category: 'web',
    icon: '💼',
    prompt: 'Create a job board with Next.js 14, company profiles, job listings with filters, application tracking, resume upload, email notifications, search functionality, featured listings, payment for premium posts, and admin dashboard.',
    tags: ['Jobs', 'Recruitment', 'Search', 'Applications', 'Payments'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'event-management',
    name: 'Event Management Platform',
    description: 'Complete event planning and ticketing system',
    category: 'web',
    icon: '🎫',
    prompt: 'Build an event management platform with Next.js 14, event creation and management, ticket sales with Stripe, QR code tickets, seating charts, calendar integration, attendee management, email notifications, and analytics dashboard.',
    tags: ['Events', 'Tickets', 'Stripe', 'QR Codes', 'Calendar'],
    complexity: 'intermediate',
    estimatedTime: '4-5 weeks',
    isPro: false,
  },
  {
    id: 'podcast-platform',
    name: 'Podcast Hosting Platform',
    description: 'Audio streaming and podcast management',
    category: 'web',
    icon: '🎙️',
    prompt: 'Create a podcast platform with Next.js 14, audio upload and transcoding, RSS feed generation, episode management, analytics dashboard, comments and reviews, subscription options, mobile app, and monetization features.',
    tags: ['Podcast', 'Audio', 'RSS', 'Streaming', 'Analytics'],
    complexity: 'advanced',
    estimatedTime: '5-6 weeks',
    isPro: true,
  },
  {
    id: 'forum-platform',
    name: 'Community Forum',
    description: 'Discussion forum with moderation tools',
    category: 'web',
    icon: '💬',
    prompt: 'Build a forum platform with Next.js 14, topic categories, threaded discussions, user profiles, moderation tools, search functionality, voting system, notifications, rich text editor, and mobile-responsive design.',
    tags: ['Forum', 'Community', 'Moderation', 'Discussions', 'Search'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'recipe-app',
    name: 'Recipe Sharing App',
    description: 'Cooking recipes with social features',
    category: 'mobile',
    icon: '👨‍🍳',
    prompt: 'Create a recipe app with React Native, recipe creation and sharing, ingredient lists, cooking timers, photo uploads, rating system, meal planning, shopping lists, nutritional information, and social features.',
    tags: ['Recipe', 'Cooking', 'Social', 'Mobile', 'Photos'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'weather-app',
    name: 'Weather Forecast App',
    description: 'Real-time weather with detailed forecasts',
    category: 'mobile',
    icon: '🌤️',
    prompt: 'Build a weather app with React Native, location-based weather data, detailed forecasts, weather maps, severe weather alerts, saved locations, beautiful animations, and offline support.',
    tags: ['Weather', 'Maps', 'Location', 'Forecasts', 'Mobile'],
    complexity: 'beginner',
    estimatedTime: '2-3 weeks',
    isPro: false,
  },
  {
    id: 'music-streaming',
    name: 'Music Streaming Service',
    description: 'Audio streaming with playlists and social features',
    category: 'web',
    icon: '🎵',
    prompt: 'Create a music streaming platform with Next.js 14, audio streaming with HLS, playlist management, user profiles, social features, recommendation algorithm, offline downloads, and mobile apps.',
    tags: ['Music', 'Streaming', 'Playlists', 'Social', 'Mobile'],
    complexity: 'advanced',
    estimatedTime: '6-7 weeks',
    isPro: true,
  },
  {
    id: 'travel-planner',
    name: 'Travel Planning Platform',
    description: 'Complete trip planning and booking system',
    category: 'web',
    icon: '✈️',
    prompt: 'Build a travel planning platform with Next.js 14, flight and hotel search, itinerary planning, budget tracking, destination guides, booking management, travel documents, and sharing features.',
    tags: ['Travel', 'Booking', 'Planning', 'Budget', 'Guides'],
    complexity: 'intermediate',
    estimatedTime: '4-5 weeks',
    isPro: false,
  },
  {
    id: 'gaming-tournament',
    name: 'Gaming Tournament Platform',
    description: 'Esports tournament management system',
    category: 'web',
    icon: '🎮',
    prompt: 'Create a gaming tournament platform with Next.js 14, tournament brackets, team management, live scoring, streaming integration, prize distribution, registration system, and match scheduling.',
    tags: ['Gaming', 'Tournament', 'Esports', 'Streaming', 'Teams'],
    complexity: 'advanced',
    estimatedTime: '5-6 weeks',
    isPro: true,
  },
  {
    id: 'language-learning',
    name: 'Language Learning App',
    description: 'Interactive language education platform',
    category: 'mobile',
    icon: '📚',
    prompt: 'Build a language learning app with React Native, interactive lessons, vocabulary builder, pronunciation practice, progress tracking, spaced repetition, social features, and offline support.',
    tags: ['Education', 'Language', 'Interactive', 'Progress', 'Mobile'],
    complexity: 'intermediate',
    estimatedTime: '4-5 weeks',
    isPro: false,
  },
  {
    id: 'crypto-wallet',
    name: 'Cryptocurrency Wallet',
    description: 'Multi-currency digital wallet interface',
    category: 'web',
    icon: '💰',
    prompt: 'Create a crypto wallet with Next.js 14, multi-currency support, transaction history, portfolio tracking, DeFi integration, security features, and mobile app.',
    tags: ['Crypto', 'Wallet', 'DeFi', 'Security', 'Mobile'],
    complexity: 'advanced',
    estimatedTime: '5-6 weeks',
    isPro: true,
  },
  {
    id: 'todo-app',
    name: 'Advanced Todo App',
    description: 'Productivity task manager with AI features',
    category: 'mobile',
    icon: '✅',
    prompt: 'Build an advanced todo app with React Native, task categorization, AI-powered suggestions, collaboration features, time tracking, habit formation, analytics, and sync across devices.',
    tags: ['Todo', 'Productivity', 'AI', 'Collaboration', 'Mobile'],
    complexity: 'beginner',
    estimatedTime: '2-3 weeks',
    isPro: false,
  },
  {
    id: 'fitness-coaching',
    name: 'Fitness Coaching Platform',
    description: 'Personal training and workout coaching app',
    category: 'mobile',
    icon: '💪',
    prompt: 'Build a fitness coaching platform with React Native, personal trainer profiles, workout plans, video demonstrations, progress tracking, nutrition guidance, community features, and video calls.',
    tags: ['Fitness', 'Coaching', 'Video', 'Mobile', 'Community'],
    complexity: 'intermediate',
    estimatedTime: '4-5 weeks',
    isPro: false,
  },
  {
    id: 'stock-trading',
    name: 'Stock Trading Platform',
    description: 'Real-time stock trading and portfolio management',
    category: 'web',
    icon: '📈',
    prompt: 'Create a stock trading platform with Next.js 14, real-time market data, portfolio management, order execution, technical analysis charts, news integration, and risk management tools.',
    tags: ['Stock Trading', 'Finance', 'Real-time', 'Charts', 'Portfolio'],
    complexity: 'advanced',
    estimatedTime: '6-7 weeks',
    isPro: true,
  },
  {
    id: 'virtual-classroom',
    name: 'Virtual Classroom Platform',
    description: 'Online education with live classes and assignments',
    category: 'web',
    icon: '🏫',
    prompt: 'Build a virtual classroom with Next.js 14, live video classes, assignment management, student progress tracking, interactive whiteboard, breakout rooms, and gradebook.',
    tags: ['Education', 'Video', 'Classroom', 'Assignments', 'Grading'],
    complexity: 'advanced',
    estimatedTime: '5-6 weeks',
    isPro: true,
  },
  {
    id: 'social-media-dashboard',
    name: 'Social Media Analytics',
    description: 'Multi-platform social media management tool',
    category: 'web',
    icon: '📊',
    prompt: 'Create a social media dashboard with Next.js 14, multi-platform integration, post scheduling, analytics tracking, engagement metrics, team collaboration, and content calendar.',
    tags: ['Social Media', 'Analytics', 'Scheduling', 'Marketing', 'Dashboard'],
    complexity: 'intermediate',
    estimatedTime: '4-5 weeks',
    isPro: false,
  },
  {
    id: 'home-automation',
    name: 'Smart Home Controller',
    description: 'IoT home automation management system',
    category: 'mobile',
    icon: '🏠',
    prompt: 'Build a smart home app with React Native, device control, automation rules, energy monitoring, security features, voice control integration, and scheduling.',
    tags: ['IoT', 'Smart Home', 'Automation', 'Security', 'Mobile'],
    complexity: 'intermediate',
    estimatedTime: '4-5 weeks',
    isPro: false,
  },
  {
    id: 'mental-health-app',
    name: 'Mental Health Tracker',
    description: 'Mood tracking and wellness journal app',
    category: 'mobile',
    icon: '🧠',
    prompt: 'Create a mental health app with React Native, mood tracking, journal entries, meditation guides, crisis support, progress analytics, and professional resources.',
    tags: ['Mental Health', 'Wellness', 'Journal', 'Meditation', 'Mobile'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'car-sharing',
    name: 'Car Sharing Platform',
    description: 'Peer-to-peer vehicle rental marketplace',
    category: 'web',
    icon: '🚗',
    prompt: 'Build a car sharing platform with Next.js 14, vehicle listings, booking system, payment processing, insurance integration, GPS tracking, and rating system.',
    tags: ['Car Sharing', 'Marketplace', 'Booking', 'GPS', 'Insurance'],
    complexity: 'advanced',
    estimatedTime: '5-6 weeks',
    isPro: true,
  },
  {
    id: 'pet-care-app',
    name: 'Pet Care Management',
    description: 'Complete pet health and care tracking system',
    category: 'mobile',
    icon: '🐕',
    prompt: 'Create a pet care app with React Native, health records, vaccination tracking, appointment scheduling, medication reminders, pet profiles, and vet finder.',
    tags: ['Pet Care', 'Health', 'Veterinary', 'Mobile', 'Reminders'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'real-estate-app',
    name: 'Real Estate Platform',
    description: 'Property listing and virtual tour platform',
    category: 'web',
    icon: '🏡',
    prompt: 'Build a real estate platform with Next.js 14, property listings, virtual tours, mortgage calculator, agent profiles, search filters, and map integration.',
    tags: ['Real Estate', 'Property', 'Virtual Tours', 'Maps', 'Mortgage'],
    complexity: 'advanced',
    estimatedTime: '6-7 weeks',
    isPro: true,
  },
  {
    id: 'volunteer-platform',
    name: 'Volunteer Matching Platform',
    description: 'Connect volunteers with organizations',
    category: 'web',
    icon: '🤝',
    prompt: 'Create a volunteer platform with Next.js 14, organization profiles, opportunity listings, volunteer matching, hour tracking, and impact analytics.',
    tags: ['Volunteer', 'Non-profit', 'Community', 'Matching', 'Analytics'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'garden-planner',
    name: 'Garden Planning App',
    description: 'Urban gardening and plant care assistant',
    category: 'mobile',
    icon: '🌱',
    prompt: 'Build a garden planning app with React Native, garden design tools, plant database, care schedules, weather integration, and harvest tracking.',
    tags: ['Gardening', 'Plants', 'Weather', 'Planning', 'Mobile'],
    complexity: 'beginner',
    estimatedTime: '2-3 weeks',
    isPro: false,
  },
  {
    id: 'bike-sharing',
    name: 'Bike Sharing System',
    description: 'Bike rental and station management platform',
    category: 'web',
    icon: '🚴',
    prompt: 'Create a bike sharing platform with Next.js 14, station mapping, bike tracking, payment integration, maintenance scheduling, and usage analytics.',
    tags: ['Bike Sharing', 'Transportation', 'GPS', 'Payments', 'Analytics'],
    complexity: 'intermediate',
    estimatedTime: '4-5 weeks',
    isPro: false,
  },
  {
    id: 'study-group-app',
    name: 'Study Group Finder',
    description: 'Connect students for collaborative learning',
    category: 'mobile',
    icon: '📚',
    prompt: 'Build a study group app with React Native, group creation, session scheduling, file sharing, video calls, whiteboard collaboration, and subject matching.',
    tags: ['Education', 'Study Groups', 'Collaboration', 'Video', 'Mobile'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'ai-image-generator',
    name: 'AI Image Generator',
    description: 'Text-to-image generation platform',
    category: 'ai',
    icon: '🎨',
    prompt: 'Create an AI image generator with Next.js 14, OpenAI DALL-E integration, prompt engineering tools, gallery management, style presets, and commercial licensing.',
    tags: ['AI', 'Image Generation', 'DALL-E', 'Art', 'Creative'],
    complexity: 'advanced',
    estimatedTime: '4-5 weeks',
    isPro: true,
  },
  {
    id: 'code-review-platform',
    name: 'Code Review Platform',
    description: 'Automated code review and quality analysis',
    category: 'devtools',
    icon: '🔍',
    prompt: 'Build a code review platform with Next.js 14, automated analysis, security scanning, performance profiling, style checking, team workflows, and integration with Git.',
    tags: ['Code Review', 'Security', 'Performance', 'Git', 'Quality'],
    complexity: 'advanced',
    estimatedTime: '5-6 weeks',
    isPro: true,
  },
  {
    id: 'api-testing-tool',
    name: 'API Testing Suite',
    description: 'Comprehensive API testing and documentation tool',
    category: 'devtools',
    icon: '🧪',
    prompt: 'Build an API testing suite with Next.js 14, automated testing, performance monitoring, documentation generation, mock servers, test data management, CI/CD integration, and team collaboration features.',
    tags: ['API Testing', 'Documentation', 'Performance', 'CI/CD', 'Testing'],
    complexity: 'advanced',
    estimatedTime: '4-5 weeks',
    isPro: true,
  },
  {
    id: 'design-system-builder',
    name: 'Design System Builder',
    description: 'Create and manage component design systems',
    category: 'devtools',
    icon: '🎨',
    prompt: 'Build a design system builder with Next.js 14, component library creation, storybook integration, design tokens management, theme generation, documentation, and export to various frameworks.',
    tags: ['Design System', 'Components', 'Storybook', 'Tokens', 'Documentation'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'microservice-generator',
    name: 'Microservice Generator',
    description: 'Generate microservice boilerplates instantly',
    category: 'devtools',
    icon: '⚙️',
    prompt: 'Create a microservice generator with Node.js, template selection, database integration, API generation, Docker setup, deployment scripts, and configuration management.',
    tags: ['Microservices', 'Generator', 'Node.js', 'Docker', 'Templates'],
    complexity: 'intermediate',
    estimatedTime: '3-4 weeks',
    isPro: false,
  },
  {
    id: 'performance-monitor',
    name: 'Performance Monitoring Dashboard',
    description: 'Real-time application performance tracking',
    category: 'devtools',
    icon: '📈',
    prompt: 'Build a performance monitoring dashboard with Next.js 14, real-time metrics, error tracking, user session recording, performance budgets, alerting, and analytics visualization.',
    tags: ['Performance', 'Monitoring', 'Analytics', 'Error Tracking', 'Real-time'],
    complexity: 'advanced',
    estimatedTime: '4-5 weeks',
    isPro: true,
  },
  {
    id: 'workflow-automation',
    name: 'Workflow Automation Tool',
    description: 'Automate development workflows and deployments',
    category: 'devtools',
    icon: '🔄',
    prompt: 'Create a workflow automation tool with GitHub integration, CI/CD pipeline builder, deployment automation, environment management, and team collaboration features.',
    tags: ['Workflow', 'Automation', 'GitHub', 'CI/CD', 'DevOps'],
    complexity: 'advanced',
    estimatedTime: '5-6 weeks',
    isPro: true,
  },
];

export const getTemplatesByCategory = (category: Template['category']) => {
  return templates.filter(t => t.category === category);
};

export const getFreeTemplates = () => {
  return templates.filter(t => !t.isPro);
};

export const getProTemplates = () => {
  return templates.filter(t => t.isPro);
};

export const getTemplateById = (id: string) => {
  return templates.find(t => t.id === id);
};
