import { TaskNode } from './planner';
import { ArchitectAgent } from './architect';
import { CodeGenerator } from '../code-generator/generator';
import { ProjectDatabase } from '../db/projects';
import { DockerRunner } from '../sandbox/docker';
import { DeploymentService } from '../deployment/deployer';

// Mock file system for V1 - in reality this would use Node.js fs or a sandboxed runner
export class ExecutionAgent {
    static async executeStep(step: TaskNode, projectId: string): Promise<string> {
        console.log(`Executing step: ${step.type} - ${step.label}`);

        switch (step.type) {
            case 'scaffold':
                return this.scaffoldProject(projectId, step.metadata);
            case 'file_create':
                return this.createFile(projectId, step.label, step.description);
            case 'command':
                return this.runCommand(projectId, step.label);
            default:
                return `Action ${step.type} simulated successfully.`;
        }
    }

    private static async scaffoldProject(projectId: string, metadata: any): Promise<string> {
        // 1. Get Project Details (Name/Description) from DB (mocking fetching for now or using metadata)
        // In reality we should fetch parameters.metadata from the step or project record.
        const projectName = metadata?.projectName || 'My VibeApp';
        const description = metadata?.description || 'A Next.js application generated by VibeCode Mentor';

        // 2. Run Architect Agent
        console.log("Running Architect Agent...");
        const blueprint = await ArchitectAgent.generateBlueprint(projectName, description);

        // 3. Run Code Generator
        console.log("Running Code Generator...");
        const generator = new CodeGenerator(blueprint);
        const generatedProject = generator.generate();

        // 4. Save to Database
        console.log("Saving to Database...");

        await ProjectDatabase.saveGeneratedBlueprint(
            projectId,
            blueprint,
            generatedProject,
            'Scaffolded by ' + generatedProject.summary.technologies[0]
        );

        // 5. Push to GitHub if connected
        let githubMessage = "";
        try {
            const { GitHubTokenDatabase } = await import('../db/github');
            const { pushProjectToGithub } = await import('../github/repository');

            // Get user_id from project
            const project = await ProjectDatabase.getProject(projectId);
            const userId = project.user_id || (project as any).user_id || (project as any).owner_id;

            const token = await GitHubTokenDatabase.getToken(userId);
            if (token) {
                console.log("Pushing to GitHub...");
                const repo = await pushProjectToGithub(
                    token.access_token,
                    generatedProject.name,
                    description,
                    generatedProject.files
                );

                // Update project with Repository info
                await ProjectDatabase.updateProjectGithubUrl(projectId, repo.repoUrl, repo.repoId);
                githubMessage = `\n\n🚀 **Live on GitHub:** [${repo.repoName}](${repo.repoUrl})`;
            }
        } catch (githubError: any) {
            console.error("GitHub sync failed:", githubError);
            githubMessage = `\n\n⚠️ **GitHub Sync Failed:** ${githubError.message}`;
        }

        return `Scaffolded ${generatedProject.files.length} files for ${generatedProject.name}. Stack: ${generatedProject.summary.technologies.join(', ')}${githubMessage}`;
    }

    private static async createFile(projectId: string, filename: string, contentDescription: string): Promise<string> {
        // In M3/M4, this triggers the LLM to write the actual code content
        // For now, we return a success message
        return `Created file ${filename} based on description: "${contentDescription}"`;
    }

    private static async runCommand(projectId: string, command: string): Promise<string> {
        // Special handling for deployment
        if (command === 'deploy') {
            const { url } = await DeploymentService.deploy(projectId);
            return `Project deployed successfully to: ${url}`;
        }

        // Run in optimized Docker Sandbox
        try {
            const logs = await DockerRunner.buildProject(projectId);
            return `Command '${command}' executed successfully.\nLogs: ${logs}`;
        } catch (e: any) {
            throw new Error(`Command failed: ${e.message}`);
        }
    }
}
