import { ProjectDatabase } from '@/lib/db/projects';
import { GitHubTokenDatabase } from '@/lib/db/github';
import { GitHubRepository } from '@/lib/github/repository';
import { GeneratedFile } from '@/lib/code-generator/types';

const API_KEY = process.env.MISTRAL_API_KEY;

export class ModificationAgent {
  /**
   * Process a modification request
   */
  static async processRequest(
    projectId: string,
    userId: string,
    userRequest: string
  ): Promise<string> {
    // 1. Get Project & GitHub Info
    const project = await ProjectDatabase.getProject(projectId);
    if (!project.github_repo_id || !project.github_url) {
      throw new Error("This project is not connected to GitHub. Please build the full app first.");
    }

    const token = await GitHubTokenDatabase.getToken(userId);
    if (!token) {
      throw new Error("GitHub token not found. Please reconnect GitHub.");
    }

    const github = new GitHubRepository(token.access_token);
    const repoOwner = project.github_url.split('/')[3];
    const repoName = project.github_url.split('/')[4];

    // 2. Identify affected files
    const affectedFiles = await this.identifyFiles(userRequest, project.generated_files.files);
    
    if (affectedFiles.length === 0) {
      return "I couldn't identify which files to modify. Could you be more specific?";
    }

    // 3. Fetch current content
    const currentFiles: GeneratedFile[] = [];
    for (const path of affectedFiles) {
      const content = await github.getFileContent(repoOwner, repoName, path, 'main');
      if (content) {
        currentFiles.push({ path, content, language: 'typescript' }); // assume TS for now
      }
    }

    if (currentFiles.length === 0) {
      return "I found the files in the blueprint but couldn't retrieve them from GitHub. The repo might be out of sync.";
    }

    // 4. Generate new code
    const updatedFiles = await this.generateCodeUpdates(userRequest, currentFiles);

    // 5. Create PR
    const branchName = `feat-${Date.now()}`;
    const prTitle = `feat: ${userRequest.substring(0, 50)}...`;
    
    await github.createBranch(repoOwner, repoName, branchName, 'main');
    await github.commitFilesToBranch(repoOwner, repoName, branchName, updatedFiles, userRequest);
    
    const pr = await github.createPullRequest(
      repoOwner, 
      repoName, 
      branchName, 
      'main', 
      prTitle, 
      `Generated by VibeCode Mentor in response to: "${userRequest}"