import { ProjectDatabase } from '@/lib/db/projects';
import { GitHubTokenDatabase } from '@/lib/db/github';
import { GitHubRepository } from '@/lib/github/repository';
import { GeneratedFile } from '@/lib/code-generator/types';

const API_KEY = process.env.MISTRAL_API_KEY;

export class ModificationAgent {
  /**
   * Process a modification request
   */
  static async processRequest(
    projectId: string,
    userId: string,
    userRequest: string
  ): Promise<string> {
    // 1. Get Project & GitHub Info
    const project = await ProjectDatabase.getProject(projectId);
    if (!project.github_repo_id || !project.github_url) {
      throw new Error("This project is not connected to GitHub. Please build the full app first.");
    }

    const token = await GitHubTokenDatabase.getToken(userId);
    if (!token) {
      throw new Error("GitHub token not found. Please reconnect GitHub.");
    }

    const github = new GitHubRepository(token.access_token);
    const repoOwner = project.github_url.split('/')[3];
    const repoName = project.github_url.split('/')[4];

    // 2. Identify affected files
    const affectedFiles = await this.identifyFiles(userRequest, project.generated_files.files);
    
    if (affectedFiles.length === 0) {
      return "I couldn't identify which files to modify. Could you be more specific?";
    }

    // 3. Fetch current content
    const currentFiles: GeneratedFile[] = [];
    for (const path of affectedFiles) {
      const content = await github.getFileContent(repoOwner, repoName, path, 'main');
      if (content) {
        currentFiles.push({ path, content, language: 'typescript' }); // assume TS for now
      }
    }

    if (currentFiles.length === 0) {
      return "I found the files in the blueprint but couldn't retrieve them from GitHub. The repo might be out of sync.";
    }

    // 4. Generate new code
    const updatedFiles = await this.generateCodeUpdates(userRequest, currentFiles);

    // 5. Create PR
    const branchName = `feat-${Date.now()}`;
    const prTitle = `feat: ${userRequest.substring(0, 50)}...`;
    
    await github.createBranch(repoOwner, repoName, branchName, 'main');
    await github.commitFilesToBranch(repoOwner, repoName, branchName, updatedFiles, userRequest);
    
    const pr = await github.createPullRequest(
      repoOwner, 
      repoName, 
      branchName, 
      'main', 
      prTitle, 
      `Generated by VibeCode Mentor in response to: "${userRequest}"`
    );

    return `I've created a Pull Request with your changes! 🎉\n\n[**${prTitle}**](${pr.html_url})\n\nReview and merge it to go live.`;
  }

  /**
   * Ask LLM which files need changing
   */
  private static async identifyFiles(request: string, allFiles: GeneratedFile[]): Promise<string[]> {
    const fileList = allFiles.map(f => f.path).join('\n');
    
    const response = await fetch('https://api.mistral.ai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${API_KEY}`,
      },
      body: JSON.stringify({
        model: 'mistral-medium-latest',
        messages: [
          { role: 'system', content: 'You are a senior developer. Return ONLY a JSON array of file paths that need to be modified to fulfill the user request. Do not include markdown formatting.' },
          { role: 'user', content: `Project Files:\n${fileList}\n\nUser Request: ${request}` }
        ],
        temperature: 0.1,
      }),
    });

    const data = await response.json();
    try {
      let content = data.choices[0].message.content;
      // Cleanup json if it has markdown
      content = content.replace(/```json/g, '').replace(/```/g, '').trim();
      return JSON.parse(content);
    } catch (e) {
      console.error("Failed to parse identified files:", e);
      return [];
    }
  }

  /**
   * Ask LLM to rewrite the code
   */
  private static async generateCodeUpdates(request: string, currentFiles: GeneratedFile[]): Promise<GeneratedFile[]> {
    const updates: GeneratedFile[] = [];

    for (const file of currentFiles) {
      const response = await fetch('https://api.mistral.ai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${API_KEY}`,
        },
        body: JSON.stringify({
          model: 'mistral-large-latest',
          messages: [
            { role: 'system', content: 'You are an expert developer. Rewrite the code to fulfill the user request. Return ONLY the full updated code content. Do not include markdown fences.' },
            { role: 'user', content: `File: ${file.path}\n\nCurrent Content:\n${file.content}\n\nUser Request: ${request}\n\nReturn the fully updated file content:` }
          ],
          temperature: 0.2,
        }),
      });

      const data = await response.json();
      let newContent = data.choices[0].message.content;
      
      // Cleanup markdown if present
      if (newContent.startsWith('```')) {
        newContent = newContent.replace(/^```[a-z]*\n/, '').replace(/```$/, '');
      }

      updates.push({
        path: file.path,
        content: newContent,
        language: file.language
      });
    }

    return updates;
  }
}
